version: "3"
services:

  app:
    image: gitlab/gitlab-ce:${VERSION_GITLAB:-latest}
    hostname: git.instantlinux.net
    command: >
      bash -c "mkdir -p /var/backups/gitlab &&
      rm -fr /var/opt/gitlab/backups &&
      ln -fnsT /var/backups/gitlab /var/opt/gitlab/backups &&
      exec /assets/wrapper"
    environment:
      TZ: ${TZ:-UTC}
    ports:
    - ${PORT_GITLAB_HTTP:-18080}:80
    - ${PORT_GITLAB_SSH:-8999}:22
    # ${PORT_GITLAB_HTTPS:-443}:443
    volumes:
    - ${SHARE_PATH}/gitlab/config:/etc/gitlab
    - ${SHARE_PATH}/gitlab/data:/var/opt/gitlab
    - backup:/var/backups
    - logs:/var/log/gitlab
    deploy:
      placement:
        constraints:
        - node.hostname == vinson
        #- ${LABEL_WORKER:-node.role == worker}
#   ulimits:
#     sigpending: 62793
#     nproc: 131072
#     nofile: 60000
#     core: 0

volumes:
  backup:
    external: true
  logs:
networks:
  default:
    external:
      name: app_net
