version: "3"
services:

  app:
    image: sonatype/nexus3:${VERSION_NEXUS:-latest}
    hostname: nexus
    environment:
      INSTALL4J_ADD_VM_PARAMS: >
        -Xms1536m -Xmx2048m -XX:MaxDirectMemorySize=3g
      TZ: ${TZ:-UTC}
    ports:
    - ${PORT_NEXUS:-8081}:8081
    - ${PORT_NEXUS_REGISTRY:-5000}:5000
    volumes:
    - /var/lib/docker/share/nexus:/nexus-data
    deploy:
      placement:
        constraints:
        - node.hostname == denali
        #- node.labels.swarm-sync-member == true

networks:
  default:
    external:
      name: app_net
