version: "3.2"
services:

# This serves nginx for Internet-facing internal services

  app:
    image: nginx:${VERSION_NGINX:-latest}
    ports:
    - target: 443
      published: 19444
      protocol: tcp
      mode: host
    - target: 80
      published: 19081
      protocol: tcp
      mode: host
    volumes:
    - ${ADMIN_PATH:-/opt}/wwwext/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    - ${SHARE_PATH}/common/pki/ca:/etc/ssl/ca:ro
    - ${SHARE_PATH}/common/pki/certs:/etc/ssl/certs:ro
    environment:
      TZ: ${TZ:-UTC}
    deploy:
      placement:
        constraints:
        - ${LABEL_WORKER:-node.role == worker}
      replicas: 2
    secrets:
    - authtotp.ci.net-server-key.pem
    - cloud.ci.net-server-key.pem
    - desktop.ci.net-server-key.pem
    - docs.ci.net-server-key.pem
    - git.instantlinux.net-server-key.pem
    - homebase.instantlinux.net-server-key.pem
    - jenkins.ci.net-server-key.pem
    - jira.ci.net-server-key.pem
    - monitor.ci.net-server-key.pem
    - repo.ci.net-server-key.pem
    - squirrelmail.ci.net-server-key.pem
    - webmail.ci.net-server-key.pem
    - www.ci.net-server-key.pem
    - www.instantlinux.net-server-key.pem

networks:
  default:
    external:
      name: app_net
secrets:
  authtotp.ci.net-server-key.pem:
    external: true
  cloud.ci.net-server-key.pem:
    external: true
  desktop.ci.net-server-key.pem:
    external: true
  docs.ci.net-server-key.pem:
    external: true
  git.instantlinux.net-server-key.pem:
    external: true
  homebase.instantlinux.net-server-key.pem:
    external: true
  jenkins.ci.net-server-key.pem:
    external: true
  jira.ci.net-server-key.pem:
    external: true
  monitor.ci.net-server-key.pem:
    external: true
  repo.ci.net-server-key.pem:
    external: true
  squirrelmail.ci.net-server-key.pem:
    external: true
  webmail.ci.net-server-key.pem:
    external: true
  www.ci.net-server-key.pem:
    external: true
  www.instantlinux.net-server-key.pem:
    external: true
